version: '3'

services:
  neo:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH=none
    volumes:
      - neo4j_data:/data/
      - exported_csv:/import
